apiVersion: v1
kind: Namespace
metadata:
  name: app-policy
  labels:
    managed-by: spyderbat-eval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: app-policy
  labels:
    app: rsvp
    tier: backend
    env: dev
    managed-by: spyderbat-eval
spec:
  selector:
    matchLabels:
      name: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb
        app: rsvp
        tier: backend
        env: dev
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        env:
        - name: MONGODB_DATABASE
          value: testdata
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: app-policy
  labels:
    app: rsvp
    tier: backend
    env: dev
    managed-by: spyderbat-eval
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    name: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-app
  namespace: app-policy
  labels:
    app: rsvp
    tier: frontend
    env: dev
    managed-by: spyderbat-eval
spec:
  selector:
    matchLabels:
      name: rsvp-app
  replicas: 3
  template:
    metadata:
      labels:
        name: rsvp-app
        app: rsvp
        tier: frontend
        env: dev
    spec:
      containers:
      - name: rsvp-app
        image: guyduchatelet/spyderbat-demo:1
        imagePullPolicy: Always
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: LINK
          value: www.spyderbat.com
        - name: COMPANY
          value: Spyderbat
        - name: TEXT1
          value: "  Rsvp demo app (dev)"
        - name: LOGO
          value: "https://s7.orientaltrading.com/is/image/OrientalTrading/PDP_VIEWER_THUMB$NOWA$/patterned-bat-magnet-craft-kit-makes-12~13778147"
        - name: DELAY
          value: "1"
        ports:
        - containerPort: 5000
          name: web-port
---
apiVersion: v1
kind: Service
metadata:
  name: rsvp-app
  namespace: app-policy
  labels:
    app: rsvp
    tier: frontend
    env: dev
    managed-by: spyderbat-eval
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    name: rsvp-app