apiVersion: v1
kind: Namespace
metadata:
  name: guidebook
  labels:
    managed-by: spyderbat-eval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guidebook-deployment
  namespace: guidebook
  labels:
    app: guidebook
    managed-by: spyderbat-eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guidebook
  template:
    metadata:
      name: guidebook
      labels:
          app: guidebook
    spec:
      containers:
        - name: spyderbat-eval-guidebook
          image: "public.ecr.aws/a6j2k0g1/spyderbat-eval-guidebook:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: guidebook-service
  namespace: guidebook
  labels:
    app: guidebook
    managed-by: spyderbat-eval
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: guidebook
