apiVersion: v1
kind: Namespace
metadata:
  name: cryptominer
  labels:
    managed-by: spyderbat-eval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: cryptominer
  labels:
    app: jupyter-notebook
    managed-by: spyderbat-eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: minimal-notebook
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
  namespace: cryptominer
  labels:
    managed-by: spyderbat-eval
spec:
  type: ClusterIP
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: jupyter
