repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.0post1
    hooks:
      - id: pre-commit-update
        args: [--dry-run]
  - repo: https://github.com/spyderbat/spyder-scan
    rev: v1.1.1
    hooks:
      - id: spyder-scan
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.83.3
    hooks:
      - id: trufflehog
        entry: trufflehog git file://. --since-commit HEAD --no-verification --fail
