repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.4.0
    hooks:
      - id: pre-commit-update
        args: [--dry-run]
  - repo: https://github.com/spyderbat/spyder-scan
    rev: v1.0.0
    hooks:
      - id: spyder-scan
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.81.9
    hooks:
      - id: trufflehog
        entry: trufflehog git file://. --since-commit HEAD --no-verification --fail
