[book]
authors = ["Spyderbat"]
language = "en"
multilingual = false
src = "src"
title = "Spyderbat Samples Guidebook"

[output.html]
additional-css = ["theme/custom.css", "fontawesome/css/all.min.css"]
default-theme = "navy"

